version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    networks:
      - laravel_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm_container
    volumes:
      - ./:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - "9000"
    networks:
      - laravel_network

  supervisor:
    image: supervisor:latest
    container_name: supervisor_container
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network

  postgresql:
    image: postgres:alpine
    container_name: postgresql_container
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - laravel_network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_container
    expose:
      - "5672"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  pgdata:
    name: "pgdata"
